### PR TITLE
update urls

### PR DESCRIPTION
**Pull request by dirk-thomas**
With the plugin being split out from `rqt_common_plugins` I will do a last release for Lunar (as well as re-release for Kinetic, Jade, and Indigo) in the next days. After that I will stop watching this repo, not look at issues and pull requests, and not perform new releases.

Someone needs to take over the maintenance role which specifically includes doing new releases. @ablasdel You are currently listed in the manifest as the maintainer. I am not sure if you want to take this role and fully take over this repository? @mikaelarguedas Since you maintain `actionlib` maybe you want to be associated with this repo? Or anyone else would like to step up (@cottsay @mrdanbrooks @130s since you have contributed to the package in the past)?

Please let me know if you want to be added / removed from the list of maintainers in the manifest. Otherwise I will go ahead and merge this as-is and release the package a last time setting the maintenance status to `unmaintained`.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
> @mikaelarguedas Since you maintain actionlib maybe you want to be associated with this repo?

I'm happy to give a hand but would appreciate co-maintainership on this one because I already have a hard time keeping up with my other maintainership commitments

**Comment by dirk-thomas** [comment]
@mikaelarguedas 62d0bf1e6b08d2647e0e7af6947a5954480d9d44 :tada:

**Comment by gbiggs** [comment]
I've not maintained a package before but I'm happy to be co-maintainer with @mikaelarguedas to learn the ropes.

**Comment by dirk-thomas** [comment]
@gbiggs That's great. Can you please create a PR to add yourself as a maintainer. @mikaelarguedas Can than merge that (so that you get notifications in the future) and add you to the repo as a collaborator.

**Pull request merged**
