### PR TITLE
Added entrypoint and setup.cfg

### PR DESCRIPTION
**Pull request by ahcorde**
Fixed package to run with `ros2 run rqt_action rqt_action`. Related to this issue https://github.com/ros-visualization/rqt_console/issues/20

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Review by ivanpauno — APPROVED** [review]
this package wasn't installing an executable at all in any platform, right?

**Comment by ahcorde** [comment]
> this package wasn't installing an executable at all in any platform, right?

 you are right

**Review by jacobperron — DISMISSED** [review]

**Comment by jacobperron** [comment]
Running `ros2 run rqt_action rqt_action` without this change, I we get "No executable found". With this change, I get the following stack trace:

```
Traceback (most recent call last):
  File "/home/jacob/ws/ros/ros-visualization_rqt_action_8/install/rqt_action/lib/rqt_action/rqt_action", line 9, in <module>
    for entry_point in distribution('rqt-action==1.0.1').entry_points:
  File "/usr/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: rqt-action==1.0.1
```

I guess since there is no executable to start with, this change isn't completely necessary?

**Comment by jacobperron** [comment]
Disregard the runtime error, looks like it's unrelated to this change. See https://github.com/ros-visualization/rqt/issues/232.

**Comment by ahcorde** [comment]
Upgrading setuptools works for you, right? can we squash and merge it?

**Comment by jacobperron** [comment]
> Upgrading setuptools works for you, right? 

Yes, that's right.

> can we squash and merge it?

It LGTM. Please update the title (since we're not changing the build type in this PR) and run CI.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11592/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6733/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9474/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11554/)

**Review by jacobperron — APPROVED** [review]

**Pull request merged**
