### PR TITLE
Add gbiggs as maintainer

### PR DESCRIPTION
**Pull request by gbiggs**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
thanks @gbiggs for joining us!

**Comment by mikaelarguedas** [comment]
@gbiggs FYI: I invited you as a collaborator of the repo

**Comment by gbiggs** [comment]
Happy to help! I'm not really sure where to start, but if you direct, I will do! :)

Although I should let you know that next week is a big holiday week here so my presence will be spotty.

**Comment by mikaelarguedas** [comment]
I'm also pretty busy the following week, we'll catch up together later on :wink: . The amount of code in this plugin seems... minimalistic. So I wouldn't be too worried about it.

**Pull request merged**
